title: <p align="center"> Seeta Ram Pandey </p>
logo: /assets/img/folder
description: 
<p align="center">
    
  <br>   
  Master’s in Electrical and Computer Engineering
  15 years of progressive advancement in the telecommunication industry
  
  <br>
  </p>

theme: jekyll-theme-minimal
